version: '3.1'

services:
  db:
    container_name: busan_db
    image: mysql
    ports:
      - '20000:3306'
    volumes:
      - busan_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: busan
      MYSQL_ROOT_PASSWORD: password
      DEFAULT_CHARACTER_SET: utf8mb4
      CHARACTER_SET_SERVER: utf8mb4
      COLLATION_SERVER: utf8mb4_general_ci
      TZ: Asia/Seoul

  spring:
    depends_on:
      - db
    image: hjaehyun25/busan-reservation:latest
    ports:
      - '8080:8080'
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_URL: jdbc:mysql://busan_db:3306/busan
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      PHONE_KEY: testesttstset
      PHONE_SECRET: testsetsetsetstsetsetsets
      PHONE_SENDER: 01012345678

volumes:
  busan_db:
