spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:20000/busan
    username: root
    password: password

phone:
  key: testesttstset
  secret: testsetsetsetstsetsetsets
