spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:20000/busan
    username: root
    password: password
  flyway:
    baseline-version: 0

phone:
  key: testesttstset
  secret: testtestesttestteststestsetstets
  sender: 01012345678

management:
  endpoints:
    web:
      exposure:
        include: prometheus
