openapi: 3.0.1
info:
  title: 회의실 대관 서비스 API
  description: 회의실 대관 서비스입니다.
  version: 1.0.0
servers:
- url: http://localhost/
tags: []
paths:
  /auth/login:
    post:
      tags:
      - auth
      operationId: 로그인하기
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/auth-login411925107'
            examples:
              로그인하기:
                value: "{\"id\":\"id\",\"password\":\"password\"}"
      responses:
        "204":
          description: "204"
  /auth/logout:
    post:
      tags:
      - auth
      operationId: 로그아웃하기
      responses:
        "204":
          description: "204"
  /auth/register:
    post:
      tags:
      - auth
      operationId: 회원가입하기
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/auth-register1438833550'
            examples:
              회원가입하기:
                value: "{\"id\":\"id\",\"password\":\"password\",\"region\":\"EMPTY\"\
                  ,\"company\":\"company\"}"
      responses:
        "201":
          description: "201"
components:
  schemas:
    auth-register1438833550:
      type: object
      properties:
        password:
          type: string
          description: "비밀번호, 공백 제외 8 ~ 30"
        company:
          type: string
          description: 회사
        id:
          type: string
          description: "아이디, 공백 제외 6 ~ 20"
        region:
          type: string
          description: 지역
    auth-login411925107:
      type: object
      properties:
        password:
          type: string
          description: 비밀번호
        id:
          type: string
          description: 아이디
