openapi: 3.0.1
info:
  title: 회의실 대관 서비스 API
  description: 회의실 대관 서비스입니다.
  version: 1.0.0
servers:
- url: http://localhost:8080
tags: []
paths:
  /admin/rooms:
    post:
      tags:
      - admin
      operationId: 회의실 생성 - 어드민
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/admin-rooms-543864538'
            examples:
              회의실 생성 - 어드민:
                value: "{\"name\":\"컨퍼런스룸 1\",\"image\":\"https://image.com\",\"maxPeopleCount\"\
                  :14,\"sequence\":1}"
      responses:
        "201":
          description: "201"
  /admin/rooms/{roomId}:
    put:
      tags:
      - admin
      operationId: 회의실 수정 - 어드민
      parameters:
      - name: roomId
        in: path
        description: ""
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/admin-rooms-543864538'
            examples:
              회의실 수정 - 어드민:
                value: "{\"name\":\"updated\",\"image\":\"updated\",\"maxPeopleCount\"\
                  :10,\"sequence\":2}"
      responses:
        "204":
          description: "204"
    delete:
      tags:
      - admin
      operationId: 회의실 삭제 - 어드민
      parameters:
      - name: roomId
        in: path
        description: 회의실 ID
        required: true
        schema:
          type: string
      responses:
        "204":
          description: "204"
  /auth/email:
    get:
      tags:
      - auth
      operationId: 휴대폰 번호로 이메일 찾기
      parameters:
      - name: phone
        in: query
        description: 인증 완료된 휴대폰 번호
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/auth-email802416584'
              examples:
                휴대폰 번호로 이메일 찾기:
                  value: "{\"emails\":[\"test@gmail.com\"]}"
  /auth/login:
    post:
      tags:
      - auth
      operationId: 로그인 하기
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/auth-login1098228858'
            examples:
              로그인 하기:
                value: "{\"email\":\"email@naver.com\",\"password\":\"password\",\"\
                  isAuto\":true}"
      responses:
        "204":
          description: "204"
  /auth/logout:
    post:
      tags:
      - auth
      operationId: 로그아웃 하기
      responses:
        "204":
          description: "204"
  /auth/phone:
    get:
      tags:
      - auth
      operationId: 받은 인증 코드로 인증 완료하기
      parameters:
      - name: code
        in: query
        description: 인증 코드
        required: true
        schema:
          type: string
      responses:
        "204":
          description: "204"
    post:
      tags:
      - auth
      operationId: 휴대폰 번호로 인증 코드 보내기
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/auth-phone2135928301'
            examples:
              휴대폰 번호로 인증 코드 보내기:
                value: "{\"phone\":\"01012312413\"}"
      responses:
        "200":
          description: "200"
  /members:
    get:
      tags:
      - members
      operationId: 현재 유저 정보 조회하기
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/members1182193868'
              examples:
                현재 유저 정보 조회하기:
                  value: "{\"name\":\"연어\",\"phone\":\"01012341234\",\"email\":\"\
                    test@naver.com\",\"role\":\"USER\",\"company\":\"우형\",\"region\"\
                    :\"BUSAN\",\"createdAt\":\"2024-01-13T18:38:16.899219\"}"
    post:
      tags:
      - members
      operationId: 회원 가입 하기
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/members-1490608316'
            examples:
              회원 가입 하기:
                value: "{\"email\":\"email@naver.com\",\"password\":\"password\",\"\
                  name\":\"name\",\"phone\":\"0101234\",\"region\":\"GANGNEUNG\",\"\
                  company\":\"company\"}"
      responses:
        "201":
          description: "201"
    delete:
      tags:
      - members
      operationId: 회원 탈퇴 하기
      responses:
        "204":
          description: "204"
  /members/password:
    put:
      tags:
      - members
      operationId: 비밀번호 분실 시 변경하기
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/members-password-1537663412'
            examples:
              비밀번호 분실 시 변경하기:
                value: "{\"email\":\"test@naver.com\",\"phone\":\"01012341234\",\"\
                  password\":\"@@newPassword123\"}"
      responses:
        "204":
          description: "204"
  /members/phone:
    put:
      tags:
      - members
      operationId: 회원 휴대폰 번호 변경하기
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/members-phone932474475'
            examples:
              회원 휴대폰 번호 변경하기:
                value: "{\"phone\":\"01012341234\"}"
      responses:
        "204":
          description: "204"
  /members/profile:
    put:
      tags:
      - members
      operationId: "회원 정보 수정하기 - 이름, 회사명"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/members-profile-1939820512'
            examples:
              회원 정보 수정하기 - 이름, 회사명:
                value: "{\"name\":\"name\",\"company\":\"company\",\"region\":\"BUSAN\"\
                  }"
      responses:
        "204":
          description: "204"
  /members/{email}:
    get:
      tags:
      - members
      operationId: 이메일 중복 확인하기
      parameters:
      - name: email
        in: path
        description: 확인할 이메일
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/members-email-1386460070'
              examples:
                이메일 중복 확인하기:
                  value: "{\"isDuplicated\":false}"
  /reservations:
    get:
      tags:
      - reservations
      operationId: 자신의 회의실 예약 목록 최신 순으로 보기
      parameters:
      - name: page
        in: query
        description: 페이지는 1부터 시작 (디폴트값 1)
        required: false
        schema:
          type: string
      - name: size
        in: query
        description: 페이지별 사이즈 (디폴트값 10)
        required: false
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reservations-all-2055281597'
              examples:
                자신의 회의실 예약 목록 최신 순으로 보기:
                  value: "{\"content\":[{\"id\":1,\"status\":\"RESERVED\",\"cancelReason\"\
                    :null,\"startTime\":\"2024-01-13T18:38:18.68911\",\"endTime\"\
                    :\"2024-01-13T20:38:18.689115\",\"name\":\"황재현\",\"phone\":\"\
                    01012341234\",\"reservedAt\":\"2024-01-13T18:38:18.689124\",\"\
                    roomId\":1,\"roomName\":\"대회의실\",\"company\":\"요기요\"},{\"id\"\
                    :2,\"status\":\"CANCELED\",\"cancelReason\":\"쓰기 싫어졌어요..\",\"\
                    startTime\":\"2024-01-13T18:38:18.689133\",\"endTime\":\"2024-01-13T20:38:18.689134\"\
                    ,\"name\":\"황재현\",\"phone\":\"01012341234\",\"reservedAt\":\"\
                    2024-01-13T18:38:18.689137\",\"roomId\":1,\"roomName\":\"대회의실\"\
                    ,\"company\":\"토스뱅크\"}],\"pageable\":\"INSTANCE\",\"last\":true,\"\
                    totalPages\":1,\"totalElements\":2,\"first\":true,\"size\":2,\"\
                    number\":0,\"sort\":{\"empty\":true,\"sorted\":false,\"unsorted\"\
                    :true},\"numberOfElements\":2,\"empty\":false}"
    post:
      tags:
      - reservations
      operationId: 회의실 예약하기
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/reservations-740649445'
            examples:
              회의실 예약하기:
                value: "{\"roomId\":1,\"startTime\":\"2023-11-10T14:00:00\",\"endTime\"\
                  :\"2023-11-10T15:00:00\"}"
      responses:
        "201":
          description: "201"
  /reservations/all:
    get:
      tags:
      - reservations
      operationId: 전체 회의실 예약 목록 최신 순으로 보기
      parameters:
      - name: page
        in: query
        description: 페이지는 1부터 시작 (디폴트값 1)
        required: false
        schema:
          type: string
      - name: size
        in: query
        description: 페이지별 사이즈 (디폴트값 10)
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/reservations-all1582432150'
            examples:
              전체 회의실 예약 목록 최신 순으로 보기:
                value: "{\"start\":\"2024-01-13T18:38:18.800506\",\"end\":\"2024-01-13T18:38:18.800508\"\
                  }"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/reservations-all-2055281597'
              examples:
                전체 회의실 예약 목록 최신 순으로 보기:
                  value: "{\"content\":[{\"id\":1,\"status\":\"RESERVED\",\"cancelReason\"\
                    :null,\"startTime\":\"2024-01-13T18:38:18.800459\",\"endTime\"\
                    :\"2024-01-13T20:38:18.800463\",\"name\":\"황재현\",\"phone\":\"\
                    01012341234\",\"reservedAt\":\"2024-01-13T18:38:18.80047\",\"\
                    roomId\":1,\"roomName\":\"대회의실\",\"company\":\"요기요\"},{\"id\"\
                    :2,\"status\":\"CANCELED\",\"cancelReason\":\"쓰기 싫어졌어요..\",\"\
                    startTime\":\"2024-01-13T18:38:18.800473\",\"endTime\":\"2024-01-13T20:38:18.800474\"\
                    ,\"name\":\"황재현\",\"phone\":\"01012341234\",\"reservedAt\":\"\
                    2024-01-13T18:38:18.800477\",\"roomId\":1,\"roomName\":\"대회의실\"\
                    ,\"company\":\"토스뱅크\"}],\"pageable\":\"INSTANCE\",\"last\":true,\"\
                    totalPages\":1,\"totalElements\":2,\"first\":true,\"size\":2,\"\
                    number\":0,\"sort\":{\"empty\":true,\"sorted\":false,\"unsorted\"\
                    :true},\"numberOfElements\":2,\"empty\":false}"
  /reservations/{reservationId}:
    put:
      tags:
      - reservations
      operationId: 자신의 회의실 예약 수정하기
      parameters:
      - name: reservationId
        in: path
        description: 수정할 예약 ID
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/reservations-740649445'
            examples:
              자신의 회의실 예약 수정하기:
                value: "{\"roomId\":1,\"startTime\":\"2023-11-10T14:00:00\",\"endTime\"\
                  :\"2023-11-10T15:00:00\"}"
      responses:
        "204":
          description: "204"
    delete:
      tags:
      - reservations
      operationId: 자신의 회의실 예약 취소하기
      parameters:
      - name: reservationId
        in: path
        description: 취소할 예약 ID
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/reservations-reservationId-361069914'
            examples:
              자신의 회의실 예약 취소하기:
                value: "{\"reason\":\"쓰기 싫어요\"}"
      responses:
        "204":
          description: "204"
  /rooms:
    get:
      tags:
      - rooms
      operationId: 회의실 전체 조회하기
      parameters:
      - name: date
        in: query
        description: 조회할 날짜 (없으면 당일 날짜로 조회됨)
        required: false
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rooms1328389190'
              examples:
                회의실 전체 조회하기:
                  value: "[{\"roomId\":1,\"name\":\"대회의실\",\"image\":\"image.com\"\
                    ,\"maxPeopleCount\":10,\"reservations\":[{\"reservationId\":1,\"\
                    startTime\":\"13:00:00\",\"endTime\":\"16:00:00\",\"isMine\":true,\"\
                    status\":\"CANCELED\",\"company\":\"우형\",\"reservedName\":\"연어\
                    \"},{\"reservationId\":2,\"startTime\":\"16:00:00\",\"endTime\"\
                    :\"17:00:00\",\"isMine\":false,\"status\":\"RESERVED\",\"company\"\
                    :\"카카오\",\"reservedName\":\"참치\"}],\"sequence\":3}]"
components:
  schemas:
    members-profile-1939820512:
      type: object
      properties:
        name:
          type: string
          description: 이름
        company:
          type: string
          description: 회사명
        region:
          type: string
          description: 지역
    reservations-740649445:
      type: object
      properties:
        startTime:
          type: string
          description: 시작 시각
        endTime:
          type: string
          description: 종료 시각
        roomId:
          type: number
          description: 예약할 회의실 ID
    auth-phone2135928301:
      type: object
      properties:
        phone:
          type: string
          description: 인증할 휴대폰 번호
    members-1490608316:
      type: object
      properties:
        password:
          type: string
          description: "특수문자 1개 이상, 영문과 숫자 조합 8 ~ 15"
        phone:
          type: string
          description: 인증 완료된 휴대폰 번호
        name:
          type: string
          description: 이름
        company:
          type: string
          description: 회사
        region:
          type: string
          description: 지역
        email:
          type: string
          description: 이메일 형식
    members-email-1386460070:
      type: object
      properties:
        isDuplicated:
          type: boolean
          description: 중복 여부
    reservations-all1582432150:
      type: object
      properties:
        start:
          type: string
          description: 시작일(포함)
        end:
          type: string
          description: 마지막일(포함)
    rooms1328389190:
      type: array
      items:
        type: object
        properties:
          sequence:
            type: number
            description: 회의실 순서
          image:
            type: string
            description: 회의실 이미지 url
          reservations:
            type: array
            items:
              type: object
              properties:
                reservationId:
                  type: number
                  description: 예약 ID
                company:
                  type: string
                  description: 예약 회사명
                startTime:
                  type: string
                  description: 예약 시작 시각
                reservedName:
                  type: string
                  description: 예약자명
                isMine:
                  type: boolean
                  description: 현재 로그인한 사람의 것인지 여부
                endTime:
                  type: string
                  description: 예약 종료 시각
                status:
                  type: string
                  description: 취소 여부
          maxPeopleCount:
            type: number
            description: 최대 수용 인원 수
          name:
            type: string
            description: 회의실 이름
          roomId:
            type: number
            description: 회의실 ID
    auth-login1098228858:
      type: object
      properties:
        password:
          type: string
          description: 비밀번호
        isAuto:
          type: boolean
          description: 자동 로그인 여부
        email:
          type: string
          description: 이메일
    admin-rooms-543864538:
      type: object
      properties:
        sequence:
          type: number
          description: 회의실 순서
        image:
          type: string
          description: 회의실 이미지 url
        maxPeopleCount:
          type: number
          description: 회의실 최대 수용 인원
        name:
          type: string
          description: 회의실 이름
    members-password-1537663412:
      type: object
      properties:
        password:
          type: string
          description: 새 비밀번호
        phone:
          type: string
          description: 인증 완료된 휴대폰 번호
        email:
          type: string
          description: 이메일
    members1182193868:
      type: object
      properties:
        createdAt:
          type: string
          description: 가입일
        role:
          type: string
          description: 계정 권한
        phone:
          type: string
          description: 휴대폰
        name:
          type: string
          description: 이름
        company:
          type: string
          description: 회사
        region:
          type: string
          description: 지역
        email:
          type: string
          description: 이메일
    auth-email802416584:
      type: object
      properties:
        emails:
          type: array
          description: 해당 번호로된 이메일 리스트
          items:
            oneOf:
            - type: object
            - type: boolean
            - type: string
            - type: number
    reservations-reservationId-361069914:
      type: object
      properties:
        reason:
          type: string
          description: 취소 사유
    reservations-all-2055281597:
      type: object
      properties:
        number:
          type: number
          description: 현재 페이지
        size:
          type: number
          description: 한 페이지당 사이즈
        numberOfElements:
          type: number
          description: 현재 응답 데이터 요소 개수
        last:
          type: boolean
          description: 마지막 페이지인지
        totalPages:
          type: number
          description: 전체 페이지 개수
        first:
          type: boolean
          description: 첫 페이지인지
        content:
          type: array
          items:
            type: object
            properties:
              phone:
                type: string
                description: 예약자 휴대폰 번호
              name:
                type: string
                description: 예약자 성함
              company:
                type: string
                description: 예약자 회사
              startTime:
                type: string
                description: 시작 시각
              endTime:
                type: string
                description: 종료 시각
              id:
                type: number
                description: 예약 ID
              reservedAt:
                type: string
                description: 예약 일시
              cancelReason:
                type: string
                description: 취소 상태일 경우 취소 이유(취소가 아니면 null)
              roomName:
                type: string
                description: 회의실 이름
              roomId:
                type: number
                description: 회의실 ID
              status:
                type: string
                description: 예약 상태
        totalElements:
          type: number
          description: 전체 DB 데이터 요소 개수
        empty:
          type: boolean
          description: 빈 데이터인지
    members-phone932474475:
      type: object
      properties:
        phone:
          type: string
          description: 인증 완료된 휴대폰 번호
